apiVersion: v2
name: grafana
description: Umbrella chart for standalone Grafana with Mimir datasource
version: 0.1.0
dependencies:
  - name: grafana
    version: "8.15.0"
    repository: https://grafana.github.io/helm-charts
