apiVersion: v2
name: grafana
description: Grafana - metrics visualization and dashboards
type: application
version: 0.1.0

dependencies:
  - name: grafana
    version: "8.8.2"
    repository: https://grafana.github.io/helm-charts
